# 是否进行文件夹初始化
initialized: True

# 是否要进行数据文件的复制及转换
excel_op: False

# 要进行处理的期数设置
time:
  第一期: False
  第二期: False
  第三期: False
  第四期: False
  第五期: True

# 初始化企业编号
company:
  制造01: 浙江恣肆科技制造有限公司
  制造02: 浙江机翼太美制造有限公司
  制造03: 浙江魔瞳制造有限公司
  制造04: 浙江斐尼柯思制造有限公司
  制造05: 浙江吾鹄科技股份有限公司
  制造06: 浙江茁恩制造有限公司
  制造07: 浙江云翼制造有限公司
  制造08: 浙江飞越制造有限公司
  制造09: 浙江起飞制造有限公司
  制造10: 浙江毅加翼科技有限公司
  制造11: 浙江雷厉速行制造有限公司
  制造12: 浙江暮叶制造有限公司
  制造13: 浙江新视眼制造有限公司
  制造14: 浙江极飞智控无人机制造有限公司
  制造15: 浙江鸿鹄制造有限公司
  制造16: 浙江高飞制造有限公司
  制造17: 浙江破尘制造有限公司
  制造18: 浙江搏长空制造有限公司
  制造19: 浙江云中游客制造有限公司
  制造20: 浙江万疆制造有限公司
  制造21: 浙江省腾蛇制造有限公司
  制造22: 浙江云中翼制造有限公司
