# 物流、供应、贸易、制造公司列表
logistic:
  - name: 浙江企鹅物流股份有限公司
    code: 物流01
  - name: 浙江响当当物流股份有限公司
    code: 物流02

supply:
  - name: 浙江铁腕供应贸易有限公司
    code: 供应01
  - name: 浙江偷着乐供应贸易有限公司
    code: 供应02
  - name: 浙江什么都有供应贸易有限公司
    code: 供应03
  - name: 浙江有点靠谱供应贸易有限公司
    code: 供应04

trade:
  - name: 浙江大慧新鹰浪贸易有限公司
    code: 贸易01
  - name: 浙江州驰贸易有限公司
    code: 贸易02
  - name: 浙江共享共创共赢贸易有限公司
    code: 贸易03
  - name: 浙江百川科技贸易有限公司
    code: 贸易04

manufacture:
  - name: 浙江超超新星制造股份有限公司
    code: 制造01
  - name: 浙江江东铁壁制造股份有限公司
    code: 制造02
  - name: 浙江东富佬制造股份有限公司
    code: 制造03
  - name: 浙江出乎意料制造有限公司
    code: 制造04
  - name: 浙江我会出手制造有限公司
    code: 制造05
  - name: 浙江异视宇宙制造股份有限公司
    code: 制造06
  - name: 浙江传信智能制造有限公司
    code: 制造07
  - name: 浙江临境生生制造股份有限公司
    code: 制造08
  - name: 浙江奶酪智能制造股份有限公司
    code: 制造09
  - name: 浙江元宇宙灵境制造股份有限公司
    code: 制造10
  - name: 浙江信姱智能制造有限公司
    code: 制造11
  - name: 浙江芯世界智能制造有限公司
    code: 制造12
  - name: 浙江第一深情制造有限公司
    code: 制造13
  - name: 浙江泰克诺勒巨制造股份有限公司
    code: 制造14
  - name: 浙江百智百戴制造股份有限公司
    code: 制造15
  - name: 浙江别具智眼制造股份有限公司
    code: 制造16
  - name: 浙江眼球环行制造有限公司
    code: 制造17
  - name: 浙江就是制造有限公司
    code: 制造18
  - name: 浙江智愈蔚来制造股份有限公司
    code: 制造19
  - name: 浙江智宝盆制造有限公司
    code: 制造20
  - name: 浙江瓯曳智能制造有限公司
    code: 制造21
  - name: 浙江彭特兰制造股份有限公司
    code: 制造22
  - name: 浙江精芯制造有限公司
    code: 制造23

# 要进行处理的期数设置
time:
  第一期: True
  第二期: True
  第三期: True
  第四期: True
  第五期: False

